### PR TITLE
WIP: Upgrade to Rails 6

### PR DESCRIPTION
**Pull request by jlecour**

### CODE REVIEW

**Comment by jlecour** [comment]
Zeitgest is causing issues : 

```
app/services/whois/parser.rb:17:in `<module:Parser>': uninitialized constant Whois::Parser::Afilias (NameError)
```

**Comment by jlecour** [comment]
@fxn Hi, since you're interested in this upgrade, you can have a look at the app, the PR and the [test suite](https://travis-ci.org/Evolix/chexpire). Thanks for your help.

**Comment by jlecour** [comment]
@fxn It looks like I have loading issues with Ruby 2.5 but not 2.6 : https://travis-ci.org/Evolix/chexpire/builds/501235599

**Comment by jlecour** [comment]
@colinux It would be great if we could discuss the necessary changes to the javascript/scss parts. I'm having a hard time finding what is custom and what needs to be changed for a good Rails 6 compatibility.

**Comment by fxn** [comment]
I am on my phone, but we could try to understand the one about `Notifier::ProcessorTest::Processor`.

Could you please enable the logger and run only the test about the processor notifier service?

**Comment by jlecour** [comment]
@fxn Sure. I’ll do this tomorrow. Thanks.

**Comment by fxn** [comment]
Perhaps related: https://github.com/rails/rails/issues/35452#issuecomment-469224956

**Comment by jlecour** [comment]
@fxn Here are the results for Ruby 2.5.1 :

```
$ bundle exec rails test -n "/#notifications_expiring_soon_can_gets_several_notifications_for_a_same_check/"
Running via Spring preloader in process 6992
Zeitwerk@rails.main: constant DomainHelper loaded from file /localhome/jlecour/work/intra/chexpire/app/helpers/domain_helper.rb
Zeitwerk@rails.main: constant CheckProcessor loaded from file /localhome/jlecour/work/intra/chexpire/app/services/check_processor.rb
Zeitwerk@rails.main: constant Notifier loaded from file /localhome/jlecour/work/intra/chexpire/app/services/notifier.rb
Zeitwerk@rails.main: constant SSL loaded from file /localhome/jlecour/work/intra/chexpire/app/services/ssl.rb
Zeitwerk@rails.main: constant Whois loaded from file /localhome/jlecour/work/intra/chexpire/app/services/whois.rb
Run options: -n /#notifications_expiring_soon_can_gets_several_notifications_for_a_same_check/ --seed 56138

# Running:

E

Error:
Notifier::ResolverTest#test_#notifications_expiring_soon_can_gets_several_notifications_for_a_same_check:
NameError: uninitialized constant Notifier::Resolver
Did you mean?  Notifier::ResolverTest
    test/services/notifier/resolver_test.rb:11:in `block in <class:ResolverTest>'


rails test test/services/notifier/resolver_test.rb:45



Finished in 0.020654s, 48.4171 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

After reading that other issue about Ruby 2.5 I came to the conclusion that I have no problem ignoring 2.5 and stay on 2.6 for now since I'm sure that it's not caused by a mistake I've made.

Thanks a lot for your help. :pray:

**Comment by fxn** [comment]
My pleasure, anything related to constants please let me know!

**Pull request merged**
